stages:
  - build
  - containerize

build disk image:
  image: registry.hackademint.org/smyler/qemu-disk-image-builder/arm:a059303f
  stage: build
  script: make image
  artifacts:
    name: Qemu vm files
    paths:
      - ubuntu.qcow2
      - downloads/QEMU_EFI.fd
  timeout: 2h

containerize:
  stage: containerize
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}"
      --destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}"

