apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: 404ctf
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
  name: log-reader
rules:
- apiGroups: [""]
  #
  # at the HTTP level, the name of the resource for accessing Log
  # objects is "logs"
  resources: ["logs", "nodes/log"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-logs-global
subjects:
- kind: ServiceAccount
  name: default
  namespace: 404ctf
roleRef:
  kind: ClusterRole
  name: log-reader
  apiGroup: rbac.authorization.k8s.io