stages:
  - build
  - containerize

compile:
  image: ubuntu@sha256:0779371f96205678dbcaa3ef499be2e5f262c8b09aadc11754bf3daf9f35e03e
  stage: build
  before_script:
    - apt-get update -qq && apt-get install -y -qq gcc gcc-multilib
  script:
    - gcc -s -m32 -Wl,-z,relro,-z,noexecstack -fno-stack-protector -Wno-stringop-overflow -no-pie la_feuille_blanche.c -o data/la_feuille_blanche
  artifacts:
    paths:
      - data/la_feuille_blanche

containerize:
  stage: containerize
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}"
  needs:
    - job: compile
      artifacts: true

